export const SuccessMessages = {
  auth: {
    SIGNUP_EMAIL: "Sign up with email successfully",
    SIGNUP_PHONE: "Sign up with phone successfully",
    SIGNIN: "Sign in successful",
    REFRESH_TOKEN: "Token refreshed successfully",
    FORGOT_PASSWORD: "Send email to get password successfully",
    FORGET_USERNAME: "Send email to get username successfully",
    RESET_PASSWORD: "Password reset successfully",
    CONFIRM_EMAIL: "Email confirmed successfully",
    RESEND_CONFIRM_EMAIL: "Confirmation email resent successfully",
    TOGGLE_2FA: "Two-Factor Authentication toggled successfully",
    LOGOUT: "Logout successfully",
    LOGOUT_FROM_ONE_DEVICE: "Logout from this device successfully",
    LOGOUT_FROM_ALL_DEVICE: "Logout from all device successfully",
  },
  user: {
    UPDATE_BIO: "User bio updated successfully",
    UPDATE_USERNAME: "Username updated successfully",
    DELETE_USER: "User deleted successfully",
    GET_ONE_USER: "Get user successfully",
    GET_ALL_USERS: "Get all user successfully",
    TOGGLE_ACTIVATE: "Toggle activation of user successfully",
    GET_LIST_DEVICES: "Get list devices successfully",
    GET_LIST_HISTORIES: "Get login history successfully",
    ADD_PROFILE_PICTURE: "Add profile picture successfully",
    ADD_THUMBNAIL: "Add thumbnail successfully",
    UPDATE_PROFILE_PICTURE: "Update profile picture successfully",
  },
  friend: {
    SEND_FRIEND_REQUEST: "Send friend request successfully",
    ACCEPT_FRIEND_REQUEST: "Accept friend request successfully",
    REJECT_FRIEND_REQUEST: "Reject friend request successfully",
    GET_LIST_FRIEND_REQUESTS: "Get list friend requests successfully",
    REMOVE_FRIEND: "Remove friend successfully",
    GET_LIST_FRIENDS: "Get list friends successfully",
    GET_MUTUAL_FRIENDS: "Get mutual friends successfully",
  },
  followers: {
    FOLLOW_USER: "Follow user successfully",
    UNFOLLOW_USER: "Unfollow user successfully",
    GET_LIST_FOLLOWERS: "Get list followers successfully",
    GET_LIST_FOLLOWINGS: "Get list followings successfully",
  },
  categories: {
    CREATE_CATEGORY: "Create new category successfully",
    UPDATE_CATEGORY: "Update category successfully",
    DELETE_CATEGORY: "Delete category successfully",
    GET_ALL_CATEGORIES: "Get all categories successfully",
    GET_CATEGORY_BY_ID: "Get category by id successfully",
    GET_CATEGORY_BY_SLUG: "Get category by slug successfully",
    GET_CATEGORIES_BY_TAG: "Get categories by tag successfully",
  },
  tags: {
    GET_ALL_TAGS: "Get all tags successfully",
    CREATE_TAG: "Create new tag successfully",
    UPDATE_TAG: "Update tag successfully",
    DELETE_TAG: "Delete tag successfully",
    ASSIGN_TAGS_TO_CATEGORY: "Assign tags to category successfully",
  },
  roles: {
    ASSIGN_ROLE_TO_USER: "Assign roles to user successfully",
    ASSIGN_PERMISSION_TO_ROLE: " Assign permissions to role successfully",
    GET_ALL_ROLES: "Get all roles successfully",
    GET_USER_ROLES: "Get user's roles successfully",
    GET_ALL_PERMISSIONS: "Get all permissions successfully",
    GET_USER_PERMISSIONS: "Get user's permissions successfully",
  },
  notifications: {
    MARK_AS_READ: "Mark as read successfully",
  },
  posts: {
    CREATE_POST: "Create new post successfully",
    REACT_TO_POST: "React to post successfully",
    GET_ALL_REACTIONS: "Get all reactions successfully",
    GET_REACTIONS_BY_TYPE: "Get post reactions by type successfully",
    GET_USER_POSTS: "Get user's posts successfully",
    GET_MY_POSTS: "Get my posts successfully",
    GET_MY_FEED: "Get my feed successfully",
    HIDE_POST_FROM_USER: "Hide posts from this user successfully",
    DELETE_POST: "Delete post successfully",
    UPDATE_POST: "Update post successfully",
    SHARE_POST: "Share post successfully",
    SEARCH_POST: "Search post successfully",
  },
  groups: {
    CREATE_GROUP: "Create new group successfully",
    GET_GROUP: "Get group successfully",
    GET_JOINED_GROUP: "Get my joined group successfully",
    GET_MANAGE_GROUP: "Get my manage group successfully",
    ADD_COVER_IMAGE: "Add group's cover image successfully",
    ADD_DESCRIPTION: "Add group's description successfully",
    INVITE_MEMBERS: "Invite members to group successfully",
    ACCEPT_INVITATION: "Accept invitation successfully",
    REJECT_INVITATION: "Reject invitation successfully",
  },
}
