export const SuccessMessages = {
  auth: {
    SIGNUP_EMAIL: "Sign up with email successfully",
    SIGNUP_PHONE: "Sign up with phone successfully",
    SIGNIN: "Sign in successful",
    REFRESH_TOKEN: "Token refreshed successfully",
    FORGOT_PASSWORD: "Forgot password initiated successfully",
    RESET_PASSWORD: "Password reset successfully",
    CONFIRM_EMAIL: "Email confirmed successfully",
    RESEND_CONFIRM_EMAIL: "Confirmation email resent successfully",
    TOGGLE_2FA: "Two-Factor Authentication toggled successfully",
    LOGOUT: "Logout successfully",
    LOGOUT_FROM_ONE_DEVICE: "Logout from this device successfully",
    LOGOUT_FROM_ALL_DEVICE: "Logout from all device successfully",
  },
  user: {
    UPDATE_BIO: "User bio updated successfully",
    UPDATE_USERNAME: "Username updated successfully",
    DELETE_USER: "User deleted successfully",
    GET_ONE_USER: "Get user successfully",
    GET_ALL_USERS: "Get all user successfully",
    TOGGLE_ACTIVATE: "Toggle activation of user successfully",
    GET_LIST_DEVICES: "Get list devices successfully",
    GET_LIST_HISTORIES: "Get login history successfully",
  },
  followers: {
    FOLLOW_USER: "Follow user successfully",
    UNFOLLOW_USER: "Unfollow user successfully",
    GET_LIST_FOLLOWERS: "Get list followers successfully",
    GET_LIST_FOLLOWINGS: "Get list followings successfully",
  },
  categories: {
    CREATE_CATEGORY: "Create new category successfully",
    UPDATE_CATEGORY: "Update category successfully",
    DELETE_CATEGORY: "Delete category successfully",
    GET_ALL_CATEGORIES: "Get all categories successfully",
    GET_CATEGORY_BY_ID: "Get category by id successfully",
    GET_CATEGORY_BY_SLUG: "Get category by slug successfully",
    GET_CATEGORIES_BY_TAG: "Get categories by tag successfully",
  },
  tags: {
    GET_ALL_TAGS: "Get all tags successfully",
    CREATE_TAG: "Create new tag successfully",
    UPDATE_TAG: "Update tag successfully",
    DELETE_TAG: "Delete tag successfully",
    ASSIGN_TAGS_TO_CATEGORY: "Assign tags to category successfully",
  },
  roles: {
    ASSIGN_ROLE_TO_USER: "Assign roles to user successfully",
    ASSIGN_PERMISSION_TO_ROLE: " Assign permissions to role successfully",
    GET_ALL_ROLES: "Get all roles successfully",
    GET_USER_ROLES: "Get user's roles successfully",
    GET_ALL_PERMISSIONS: "Get all permissions successfully",
    GET_USER_PERMISSIONS: "Get user's permissions successfully",
  },
  notifications: {
    MARK_AS_READ: "Mark as read successfully",
  },
}
